import React from "react";

import { Article } from "../components/articles/Article";
import { ExternalLink } from "../components/articles/ExternalLink";

const IntroductionToPython = () => {
  return (
    <main className="main">
      <Article
        title={"Introduction to Python"}
        subtitle={"Yet another python guide"}
      >
        <h3 id="what-is-python-and-why-you-should-learn-it">
          What is Python and why you should learn it
        </h3>
        <p>
          <ExternalLink href="https://www.python.org/">Python</ExternalLink> is
          a high-level programming language created by Guido van Rossum. It was
          released in 1991. Although images of snakes are often associated with
          Python, the name is actually derived from Guido van Rossum's favorite
          TV show, "Monty Python's Flying Circus". Python is an object-oriented
          programming language which is available on a wide variety of systems
          and can be used for a lot of different applications. The current
          version is Python 3, which will be the focus of the following
          explanations. Python is designed to be a beginner-friendly yet
          powerful programming language. In recent years, Python has gained
          increasing popularity, especially due to well-known and robust
          frameworks designed for scientific computing, artificial intelligence,
          and data science. Examples of such frameworks include{" "}
          <ExternalLink href="https://numpy.org/">Numpy</ExternalLink>,{" "}
          <ExternalLink href="https://pandas.pydata.org/">Pandas</ExternalLink>,{" "}
          <ExternalLink href="https://pytorch.org/">PyTorch</ExternalLink> or{" "}
          <ExternalLink href="https://www.tensorflow.org/">
            TensorFlow
          </ExternalLink>
          . Python is also commonly used for automation, prototyping, and even
          web development.
        </p>
        <p>
          Unlike many other programming languages, Python statements do not
          require termination with a special character. The Python interpreter
          identifies the end of a statement through the presence of a newline,
          generated by pressing the "Return" key on the keyboard. We will delve
          into multi-line statements in subsequent sections. Another crucial
          point to note is that Python relies on indentation instead of
          delimiters like curly braces. While the specific amount of indentation
          doesn't hold significance, it must remain consistent within a given
          depth of a loop or conditional statement. Additionally, statements
          that are not intended to be indented must start from the first column.
          However, adhering to the convention outlined in{" "}
          <ExternalLink href="https://peps.python.org/pep-0008/">
            PEP 8
          </ExternalLink>
          , it is recommended to use 4 spaces for indentation, a practice we'll
          explore further in upcoming discussions.
        </p>

        <h3 id="setting-up-a-python-environment">
          Setting up a Python environment
        </h3>
        <p>
          Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
          nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
          sed diam voluptua. At vero eos et accusam et justo duo dolores et ea
          rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem
          ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur
          sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
          dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam
          et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
          takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit
          amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
          invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
          At vero eos et accusam et justo duo dolores et ea rebum. Stet clita
          kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
          amet. Duis autem vel eum iriure dolor in hendrerit in vulputate velit
          esse molestie consequat, vel illum dolore eu feugiat nulla facilisis
          at vero eros et accumsan et iusto odio dignissim qui blandit praesent
          luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
          nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat
          volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation
          ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
          Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse
        </p>

        <h3 id="variables">Variables</h3>
        <p>
          <iframe
            src="https://trinket.io/embed/python/3d8d7ce66b"
            width="100%"
            height="356"
            frameborder="0"
            marginwidth="0"
            marginheight="0"
            allowfullscreen
            // can we somehow set the color scheme?
          ></iframe>
        </p>
      </Article>
    </main>
  );
};

export { IntroductionToPython };
